# fly.toml app configuration file generated for messaging-board-jana on 2023-06-05T17:09:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messaging-board-jana"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
